### ISSUE TITLE
trouble while loading jpg

### ISSUE THREAD

**Issue by marcrleonard** [jcupitt/pyvips#24]
I am running OSX. I've homebrew'd vips, the pip installed pyvips. In an attempt to load a jpeg image, I've gotten an error. Here is my code:

```
import pyvips
image = pyvips.Image.new_from_file(vips_filename="IMG_0015_guides.jpg")
```
error:
```
(process:43653): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:43653): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:43653): GLib-GObject-WARNING **: g_object_set_is_valid_property: object class '(null)' has no property named 'filename'
Traceback (most recent call last):
  File "/Users/marcleonard/Sites/asvcu_dev/www/FlaskApp/FlaskApp/ArtstreamVideoWorkflow/test.py", line 3, in <module>
    image = pyvips.Image.new_from_file(vips_filename="IMG_0015_guides.jpg")
  File "/Users/marcleonard/anaconda3/lib/python3.6/site-packages/pyvips/vimage.py", line 254, in new_from_file
    ), **kwargs)
  File "/Users/marcleonard/anaconda3/lib/python3.6/site-packages/pyvips/voperation.py", line 213, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignLoadJpegFile
  jpegload: parameter filename not set
```

**Comment by jcupitt** [comment]
Hello, trty:

```python
image = pyvips.Image.new_from_file("IMG_0015_guides.jpg")
```

**Comment by marcrleonard** [comment]
same result :-/

**Comment by jcupitt** [comment]
Could you paste the exact code and output? For example, I see:

```
$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> 
```

What if you try with Apple or Homebrew's Python? The anaconda one is a little strange.

**Comment by marcrleonard** [comment]
No problem. Here you go:

```
Marcs-MacBook-Pro:Workflow leonard$ python3
Python 3.6.2 |Anaconda, Inc.| (default, Sep 21 2017, 18:29:43) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> image = pyvips.Image.new_from_file("IMG_0015_guides.jpg")

(process:98284): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:98284): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:98284): GLib-GObject-WARNING **: g_object_set_is_valid_property: object class '(null)' has no property named 'filename'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/marcleonard/anaconda3/lib/python3.6/site-packages/pyvips/vimage.py", line 254, in new_from_file
    ), **kwargs)
  File "/Users/marcleonard/anaconda3/lib/python3.6/site-packages/pyvips/voperation.py", line 213, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call VipsForeignLoadJpegFile
  jpegload: parameter filename not set


```

**Comment by marcrleonard** [comment]
Ok, thanks for the help John. With a fresh venv with the official python3 download, it worked properly. Thank you!

**Comment by jcupitt** [comment]
Anaconda seems to really need its own package :(
