### ISSUE TITLE
'dpi' kwarg raises exception for TIFF images

### ISSUE THREAD

**Issue by geniass** [jcupitt/pyvips#29]
This occurs if you use the same code to load PDFs and TIFFs. PDFs require a DPI while TIFFs don't, which is fine. The problem is that the error message is a bit vague.

There should either be a better error/warning message ("DPI is not supported for filetype of TIFF") or the dpi parameter should be ignored.

Minimal example:
```python
>>> import pyvips

# loading with no kwargs works fine
>>> pyvips.Image.new_from_file("/tmp/test_document.tiff")
<pyvips.Image 2480x3507 uchar, 1 bands, b-w>

# specifying dpi fails with slightly obscure error:
>>> pyvips.Image.new_from_file("/tmp/test_document.tiff", dpi=100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/app/venv/lib/python3.5/site-packages/pyvips/vimage.py", line 254, in new_from_file
    ), **kwargs)
  File "/home/app/venv/lib/python3.5/site-packages/pyvips/voperation.py", line 208, in call
    op.set(name, flags_from_name[name], match_image, value)
KeyError: 'dpi'
```

**Comment by jcupitt** [comment]
Hello @geniass,

If you know the filetype, I would use the format-specific loader. Your IDE should be able to tell you what args it supports:

```
>>> help(pyvips.Image.svgload)
Help on function call_function in module pyvips.vimage:

call_function(*args, **kwargs)
    Load SVG with rsvg.
    
    Example:
       out = pyvips.Image.svgload(filename, memory = bool, access = str, dpi = float, fail = bool, scale = float)
    
    Returns:
        out (Image): Output image
    
    Args:
        filename (str): Filename to load from
    
    Keyword args:
        memory (bool): Force open via memory
        access (str): Required access pattern for this file
        dpi (float): Render at this DPI
        fail (bool): Fail on first error
        scale (float): Scale output by this factor
    
    Other Parameters:
...
```

I agree the error message could be better. How about:

```
>>> import pyvips
>>> x = pyvips.Image.new_from_file("/home/john/pics/wtc.tif", dpi=200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyvips/vimage.py", line 216, in new_from_file
    ), **kwargs)
  File "pyvips/voperation.py", line 181, in call
    '{1}'.format(operation_name, name))
pyvips.error.Error: VipsForeignLoadTiffFile does not support argument dpi
```

**Comment by jcupitt** [comment]
OK, the new message is in. Thanks!
