### ISSUE TITLE
import pyvips throws exception for python 2.7 in AWS lambda (ZLIB_1.2.9 not found while loading libvips.so.42)

### ISSUE THREAD

**Issue by munirhossain** [jcupitt/pyvips#42]
I'm writing a AWS Lambda function using pyvips python package. But it throws exception when `import pyvips` is executed. The error is as follows. I've zipped cffi, pycparser, pyvips and a lib directory which contains all the shared libraries of libvips for [lambda build package](https://libraries.io/github/stechstudio/libvips-lambda). I've also set the environment variable `LD_LIBRARY_PATH=./lib:LD_LIBRARY_PATH` .The lambda.zip that I'm uploading to the AWS lambda can be found [here](https://drive.google.com/file/d/1ka8gF9E8C6BydVf4Gw4R1__9Fa8LUgYc/view?usp=sharing).

```START RequestId: af867599-5876-11e8-a3ca-ffec3ebba19d Version: $LATEST
cannot load library 'libvips.so.42': /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by ./lib/libpng16.so.16).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42': OSError
Traceback (most recent call last):
  File "/var/task/lambda.py", line 5, in lambda_handler
    import pyvips
  File "/var/task/pyvips/__init__.py", line 54, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/var/task/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/var/task/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/var/task/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': /lib64/libz.so.1: version `ZLIB_1.2.9' not found (required by ./lib/libpng16.so.16).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'

END RequestId: af867599-5876-11e8-a3ca-ffec3ebba19d
REPORT RequestId: af867599-5876-11e8-a3ca-ffec3ebba19d	Duration: 459.45 ms	Billed Duration: 500 ms 	Memory Size: 128 MB	Max Memory Used: 21 MB	
```
This may not be a problem of libvips or pyvips but some setting in AWS Lambda function that I don't know.

**Comment by jcupitt** [comment]
Hello, I'll have a go at a docker build on aws.

**Comment by jcupitt** [comment]
This seems to work:

https://github.com/jcupitt/docker-builds/tree/master/pyvips-aws

Though I don't know if that'll help you much.

**Comment by munirhossain** [comment]
I think docker would be fine since it manages all its libraries. In my case I'm running a Lambda function without docker. And the problem is that even though I provide all the necessary libraries in lib directory and set the environment path `LD_LIBRARY_PATH=./lib`. It seems Lambda in unable to load all the libraries from this `lib` directory. I've found a work around which is running another process with my correct configuration set for the library path and load pyvips in that process only. It seems to work. It is a work around and the down side is that you need to create another process and manage it. So it comes with all the regular downside of it. But for now it is working fine. I mainly posted it here for the community and the AWS team to look into. This is not a VIPS problem and I'll update here if I find anything better.

**Comment by baxhul** [comment]
@munirhossain I am currently having the same problem. Did you manage to make it work? If not can you please explain your workaround?

**Comment by baxhul** [comment]
@munirhossain I managed to made it work. Had some fun replacing some dependencies from your package and at some point it worked: 

https://drive.google.com/file/d/1dIuyObvLWlTFGDhzFS7EY5ikNNvNfHw1/view

**Comment by AntonOellerer** [comment]
Hey @baxhul could you maybe report how you solved the issue in more detail?
I am facing the same right now.

**Comment by sandes** [comment]
FROM public.ecr.aws/lambda/python:3.8


# general build stuff
RUN yum update -y \
	&& yum groupinstall -y "Development Tools" \
	&& yum install -y wget tar

# libvips needs libwebp 0.5 or later and the one on amazonlinux2 is 0.3.0, so
# we have to build it ourselves

# packages needed by libwebp
RUN yum install -y \
	libjpeg-devel \
	libpng-devel \
	libtiff-devel \
	libgif-devel

# stuff we need to build our own libvips ... this is a pretty basic selection
# of dependencies, you'll want to adjust these
# dzsave needs libgsf
RUN yum install -y \
	libpng-devel \
	poppler-glib-devel \
	glib2-devel \
	libjpeg-devel \
	expat-devel \
	zlib-devel \
	orc-devel \
	lcms2-devel \
	libexif-devel \
	libgsf-devel


RUN yum install -y \
	 https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm


RUN yum install -y yum-utils

RUN yum install -y http://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum-config-manager --enable remi

RUN yum install -y \
	vips \
	vips-devel \
	vips-tools


# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY app.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]
