### ISSUE TITLE
OSError: cannot load library 'C:\Program Files\vips-dev-8.6\bin\libvips-42.dll': error 0xc1

### ISSUE THREAD

**Issue by zhanghaoyue** [jcupitt/pyvips#64]
Hello,

I used pyvips on Linux and everything worked pretty well. Now I try to set up pyvips on Windows. Following the instruction and setting path in environment variable, I got this error:

Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/HaoyueZhang/Documents/GitHub/prediction_overlay/venv/overlay_Mask_R.py", line 9, in <module>
    import pyvips
  File "C:\Python37-32\lib\site-packages\pyvips\__init__.py", line 69, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "C:\Python37-32\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Python37-32\lib\site-packages\cffi\api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Python37-32\lib\site-packages\cffi\api.py", line 798, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'C:\Program Files\vips-dev-8.6\bin\libvips-42.dll': error 0xc1

I saw another issue similar to this one so I tried moving the VIPS path to top, still no luck.

In command line I get correct output from "vips"
Usage:
  vips [OPTIONâ?▌] [ACTION] [OPTIONS] [PARAMETERS] - VIPS driver program

Help Options:
  -h, --help                    Show help options

Application Options:
  -l, --list=BASE-NAME          list objects
  -p, --plugin=PLUGIN           load PLUGIN
  -v, --version                 print version
  --vips-concurrency=N          evaluate with N concurrent threads
  --vips-progress               show progress feedback
  --vips-leak                   leak-check on exit
  --vips-profile                profile and dump timing on exit
  --vips-disc-threshold=N       images larger than N are decompressed to disc
  --vips-novector               disable vectorised versions of operations
  --vips-cache-max=N            cache at most N operations
  --vips-cache-max-memory=N     cache at most N bytes in memory
  --vips-cache-max-files=N      allow at most N open files
  --vips-cache-trace            trace operation cache
  --vips-cache-dump             dump operation cache on exit
  --vips-version                print libvips version

**Comment by zhanghaoyue** [comment]
Hello @jcupitt 
I tried your suggestions together and still got the same issue.

C:\vips>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
Traceback (most recent call last):
  File "C:\Python37-32\lib\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37-32\lib\site-packages\pyvips\__init__.py", line 69, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "C:\Python37-32\lib\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Python37-32\lib\site-packages\cffi\api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Python37-32\lib\site-packages\cffi\api.py", line 798, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'C:\vips\bin\libvips-42.dll': error 0xc1

Could it be possible that vips is 64 bit and my python is 32?

**Comment by jcupitt** [comment]
Yes, that would certainly do it. The libvips binary we support is 64 bit.

libvips can build as 32-bit, but you'd need to make it yourself.

**Comment by zhanghaoyue** [comment]
Come back to confirm this issue is solved by making sure they are both 64 bit
