### ISSUE TITLE
test suite on Windows

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/pyvips#8]
The test suite currently fails on Windows due to temp file handling. We should do something better to remove files we're finished with.

**Comment by jcupitt** [comment]
Seems to be fixed!

**Comment by kleisauke** [comment]
This was not fixed yet, I still see (with libvips 8.5.8):
<details>
 <summary>Output</summary>

```bash
............................................................................................................................................E........E.EE........................................
======================================================================
ERROR: test_jpeg (pyvips.tests.test_foreign.TestForeign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 172, in test_jpeg
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\KLEISA~1\\AppData\\Local\\Temp\\tmp33488d43.jpg'

======================================================================
ERROR: test_rad (pyvips.tests.test_foreign.TestForeign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 623, in test_rad
    self.rad, max_diff=0)
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 97, in save_buffer_tempfile
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\KLEISA~1\\AppData\\Local\\Temp\\tmpzvo_vrza.hdr'

======================================================================
ERROR: test_tiff (pyvips.tests.test_foreign.TestForeign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 226, in test_tiff
    self.save_load_file(".tif", "[squash]", self.onebit, 0)
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 71, in save_load_file
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\KLEISA~1\\AppData\\Local\\Temp\\tmpc6g6vhug.tif'

======================================================================
ERROR: test_vips (pyvips.tests.test_foreign.TestForeign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 100, in test_vips
    self.save_load_file(".v", "", self.colour, 0)
  File "S:\Users\KleisAuke\Documents\GitHub\pyvips\pyvips\tests\test_foreign.py", line 71, in save_load_file
    os.unlink(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\KLEISA~1\\AppData\\Local\\Temp\\tmpo9ly79uj.v'

----------------------------------------------------------------------
Ran 193 tests in 43.470s

FAILED (errors=4)
```
</details>

Therefore created #11 to fix this.

**Comment by jcupitt** [comment]
Ooop, you're right, I was thinking of the Ruby binding. Sad!

**Comment by jcupitt** [comment]
OK, nice work Kleis, closing again.

**Comment by jcupitt** [comment]
ok v2.0.1 pushed to pypi
